# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-26 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0003_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Event Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='guests',
            field=models.ManyToManyField(blank=True, to='rsvp.Guest'),
        ),
        migrations.AlterField(
            model_name='event',
            name='vendors',
            field=models.ManyToManyField(blank=True, to='rsvp.Vendor'),
        ),
    ]
