# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-26 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0004_auto_20170226_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='owners',
            field=models.ManyToManyField(blank=True, to='rsvp.Owner'),
        ),
    ]
