# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0007_auto_20170227_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicequestion',
            name='vendors',
            field=models.ManyToManyField(blank=True, to='rsvp.Vendor'),
        ),
        migrations.AddField(
            model_name='textquestion',
            name='vendors',
            field=models.ManyToManyField(blank=True, to='rsvp.Vendor'),
        ),
        migrations.AddField(
            model_name='textresponse',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
