# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-01 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0009_auto_20170301_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicequestion',
            name='finalized',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textquestion',
            name='finalized',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
