# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0013_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
    ]
